version: '3.8'

services:
  auth-srv:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "8006:8006"
    env_file:
      - .env.dev
  auth-mongo-srv:
    image: mongo:5.0.2
    ports:
      - "27020:27017"
    logging:
      driver: none
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
